### ISSUE TITLE
Step 3 in instructions throws an error

### ISSUE THREAD

**Issue by chaosloth** [slintab/twilio-flex-terraform#1]
Following the instructions in the README the command in step 3 (bullet point 1) throws an error.

Steps to reproduce:
`terraform import module.routing twilio_taskrouter_workspaces_v1.flex <WORKSPACE_SID>`.

Results in:
`(base) ➜  dev git:(main) ✗ terraform import module.routing twilio_taskrouter_workspaces_v1.flex <WORKSPACE_SID> 
The import command expects two arguments.
Usage: terraform [global options] import [options] ADDR ID
...`

Notes:
The second command works fine

**Comment by slintab** [comment]
Thanks for spotting this! 

There should not be a space between `module.routing` and `twilio_taskrouter_workspaces_v1.flex`.
Instead, the correct syntax for the import command should read as: 
`terraform import module.routing.twilio_taskrouter_workspaces_v1.flex <WORKSPACE_SID>`.

I will update the readme, too, in a sec. :)
